# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd385b2dd7e07840fe016bde7acbb4b6764a1765de26d7baf8c60216f71ffe0c5bd4cf9f27a30396a075e1f1b0a3427d65c221207aa875510b150a7ce07049ad

test:
  secret_key_base: 7843af5a6e5ec0f8e886144ec3f9465209c9cf649e5b40eb4aba2c9133d3d815f92e9a08b8198a2aa588d359ceab5ba026d7feb8f4fe7923480ba74f69434a3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 7843af5a6e5ec0f8e886144ec3f9465209c9cf649e5b40eb4aba2c9133d3d815f92e9a08b8198a2aa588d359ceab5ba026d7feb8f4fe7923480ba74f69434a3d
